# Generated by Django 6.0.5 on 2026-05-08 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenIdConnectProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sub", models.CharField(max_length=255, unique=True)),
                ("access_token", models.TextField(null=True)),
                ("expires_before", models.DateTimeField(null=True)),
                ("refresh_token", models.TextField(null=True)),
                ("refresh_expires_before", models.DateTimeField(null=True)),
                ("id_token", models.TextField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "swappable": "KEYCLOAK_OIDC_PROFILE_MODEL",
            },
        ),
    ]
